
// Generated by Cadence Genus(TM) Synthesis Solution 19.11-s087_1
// Generated on: Jun  1 2021 16:31:47 CEST (Jun  1 2021 14:31:47 UTC)

// Verification Directory fv/booth_multiply 

module booth_multiply(clk, rst, a_in, b_in, r_out, start, ready);
  input clk, rst, start;
  input [7:0] a_in, b_in;
  output [15:0] r_out;
  output ready;
  wire clk, rst, start;
  wire [7:0] a_in, b_in;
  wire [15:0] r_out;
  wire ready;
  wire [16:0] temp_reg;
  wire [16:0] P_reg;
  wire [16:0] A_reg;
  wire [16:0] S_reg;
  wire [3:0] i_reg;
  wire [2:0] state_reg;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire UNCONNECTED23, UNCONNECTED24, UNCONNECTED25, UNCONNECTED26,
       UNCONNECTED27, UNCONNECTED28, UNCONNECTED29, UNCONNECTED30;
  wire UNCONNECTED31, UNCONNECTED32, UNCONNECTED33, UNCONNECTED34,
       UNCONNECTED35, UNCONNECTED36, UNCONNECTED37, UNCONNECTED38;
  wire UNCONNECTED39, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_44, n_45, n_46, n_47;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_80;
  wire n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_89, n_90, n_91, n_92, n_93, n_94, n_95, n_96;
  wire n_97, n_98, n_99, n_100, n_101, n_102, n_103, n_104;
  wire n_105, n_106, n_107, n_108, n_109, n_110, n_111, n_112;
  wire n_113, n_114, n_115, n_116, n_117, n_118, n_119, n_120;
  wire n_121, n_122, n_123, n_124, n_125, n_126, n_127, n_128;
  wire n_129, n_130, n_131, n_132, n_133, n_134, n_135, n_136;
  wire n_137, n_138, n_139, n_140, n_141, n_142, n_143, n_144;
  wire n_145, n_146, n_147, n_148, n_149, n_150, n_151, n_152;
  wire n_153, n_154, n_155, n_156, n_157, n_158, n_159, n_160;
  wire n_161, n_162, n_163, n_164, n_165, n_166, n_167, n_168;
  wire n_169, n_170, n_171, n_172, n_173, n_174, n_175, n_176;
  wire n_177, n_178, n_179, n_180, n_181, n_182, n_183, n_184;
  wire n_185, n_186, n_187, n_188, n_189, n_190, n_191, n_192;
  wire n_193, n_194, n_195, n_196, n_197, n_198, n_199, n_200;
  wire n_201, n_202, n_203, n_204, n_205, n_206, n_207, n_208;
  wire n_209, n_210, n_211, n_212, n_213, n_214, n_215, n_216;
  wire n_217, n_218, n_219, n_220, n_221, n_222, n_223, n_224;
  wire n_225, n_226, n_227, n_228, n_229, n_230, n_231, n_232;
  wire n_233, n_234, n_235, n_236, n_237, n_238, n_239, n_240;
  wire n_241, n_242, n_243, n_244, n_245, n_246, n_247, n_248;
  wire n_249, n_250, n_251, n_252, n_253, n_273;
  assign r_out[14] = r_out[15];
  DFC3 \temp_reg_reg[16] (.RN (n_252), .C (clk), .D (n_253), .Q
       (temp_reg[16]), .QN (UNCONNECTED));
  wire w;
  nand g8135 (n_253, w, n_249, n_248);
  or g (w, n_251, n_241);
  DFC3 \temp_reg_reg[15] (.RN (n_252), .C (clk), .D (n_250), .Q
       (temp_reg[15]), .QN (UNCONNECTED0));
  wire w0, w1;
  nand g8139 (n_251, w0, w1);
  or g1 (w1, temp_reg[16], n_246);
  or g0 (w0, n_233, n_245);
  wire w2;
  nand g8137 (n_250, w2, n_249, n_247);
  or g3 (w2, n_240, n_76);
  nand g8140 (n_248, n_75, n_244);
  wire w3;
  nand g8141 (n_247, w3, n_98, n_243);
  or g4 (w3, n_246, temp_reg[15]);
  wire w4, w5, w6, w7, w8, w9, w10;
  nand g8144 (n_245, w6, w10);
  or g11 (w10, w9, P_reg[15]);
  and g10 (w9, w7, w8);
  nand g9 (w8, A_reg[16], n_237);
  or g8 (w7, A_reg[16], n_237);
  nand g7 (w6, w4, w5, P_reg[15]);
  nand g6 (w5, A_reg[16], n_237);
  or g5 (w4, A_reg[16], n_237);
  wire w11, w12, w13, w14, w15, w16, w17;
  nand g8145 (n_244, w13, w17);
  or g18 (w17, w16, P_reg[15]);
  and g17 (w16, w14, w15);
  nand g16 (w15, S_reg[16], n_239);
  or g15 (w14, S_reg[16], n_239);
  nand g14 (w13, w11, w12, P_reg[15]);
  nand g13 (w12, S_reg[16], n_239);
  or g12 (w11, S_reg[16], n_239);
  DFC3 \temp_reg_reg[14] (.RN (n_252), .C (clk), .D (n_242), .Q
       (temp_reg[14]), .QN (n_11));
  nand g8146 (n_243, n_223, n_238);
  wire w18;
  nand g8147 (n_242, w18, n_235);
  or g19 (w18, n_234, n_241);
  wire w19, w20, w21, w22, w23, w24, w25, w26;
  wire w27, w28, w29, w30, w31, w32;
  nand g34 (n_240, w26, w32);
  or g33 (w32, w31, n_1);
  and g32 (w31, w28, w30);
  nand g31 (w30, w29, n_227);
  not g30 (w29, n_236);
  nand g29 (w28, w27, n_236);
  not g28 (w27, n_227);
  nand g27 (w26, w23, w25, n_1);
  nand g26 (w25, w24, n_227);
  not g25 (w24, n_236);
  nand g24 (w23, w22, n_236);
  not g23 (w22, n_227);
  and g8149 (n_239, w20, w21);
  or g22 (w21, n_227, n_236);
  or g21 (w20, w19, n_1);
  and g20 (w19, n_227, n_236);
  wire w33, w34, w35, w36, w37, w38, w39, w40;
  wire w41, w42, w43, w44, w45, w46;
  nand g49 (n_238, w40, w46);
  or g48 (w46, w45, A_reg[15]);
  and g47 (w45, w42, w44);
  nand g46 (w44, w43, n_229);
  not g45 (w43, n_236);
  nand g44 (w42, w41, n_236);
  not g43 (w41, n_229);
  nand g42 (w40, w37, w39, A_reg[15]);
  nand g41 (w39, w38, n_229);
  not g40 (w38, n_236);
  nand g39 (w37, w36, n_236);
  not g38 (w36, n_229);
  and g8150 (n_237, w34, w35);
  or g37 (w35, n_229, n_236);
  or g36 (w34, w33, A_reg[15]);
  and g35 (w33, n_229, n_236);
  wire w47, w48;
  nand g8151 (n_235, w47, w48);
  or g51 (w48, n_162, n_150);
  or g50 (w47, n_151, n_232);
  wire w49, w50;
  nand g8154 (n_234, w49, w50);
  or g53 (w50, temp_reg[14], n_246);
  or g52 (w49, n_233, n_231);
  nor g8156 (n_232, n_228, n_130);
  DFC3 \temp_reg_reg[13] (.RN (n_252), .C (clk), .D (n_226), .Q
       (temp_reg[13]), .QN (UNCONNECTED1));
  not g8157 (n_231, n_230);
  wire w51, w52, w53, w54, w55, w56, w57, w58;
  wire w59, w60, w61, w62, w63, w64;
  nand g68 (n_230, w58, w64);
  or g67 (w64, w63, A_reg[14]);
  and g66 (w63, w60, w62);
  nand g65 (w62, w61, n_218);
  not g64 (w61, P_reg[14]);
  nand g63 (w60, w59, P_reg[14]);
  not g62 (w59, n_218);
  nand g61 (w58, w55, w57, A_reg[14]);
  nand g60 (w57, w56, n_218);
  not g59 (w56, P_reg[14]);
  nand g58 (w55, w54, P_reg[14]);
  not g57 (w54, n_218);
  and g8158 (n_229, w52, w53);
  or g56 (w53, n_218, P_reg[14]);
  or g55 (w52, w51, A_reg[14]);
  and g54 (w51, n_218, P_reg[14]);
  wire w65, w66, w67, w68, w69, w70, w71, w72;
  wire w73, w74, w75, w76, w77, w78;
  nand g83 (n_228, w72, w78);
  or g82 (w78, w77, n_2);
  and g81 (w77, w74, w76);
  nand g80 (w76, w75, n_220);
  not g79 (w75, P_reg[14]);
  nand g78 (w74, w73, P_reg[14]);
  not g77 (w73, n_220);
  nand g76 (w72, w69, w71, n_2);
  nand g75 (w71, w70, n_220);
  not g74 (w70, P_reg[14]);
  nand g73 (w69, w68, P_reg[14]);
  not g72 (w68, n_220);
  and g8159 (n_227, w66, w67);
  or g71 (w67, n_220, P_reg[14]);
  or g70 (w66, w65, n_2);
  and g69 (w65, n_220, P_reg[14]);
  not g8160 (n_226, n_225);
  nor g8161 (n_225, n_224, n_222);
  DFEC1 \S_reg_reg[16] (.RN (n_252), .C (clk), .D (n_215), .E (n_217),
       .Q (S_reg[16]), .QN (UNCONNECTED2));
  wire w79;
  nor g8164 (n_224, w79, n_99);
  and g84 (w79, n_223, n_219);
  wire w80;
  nor g8165 (n_222, w80, n_71);
  and g85 (w80, n_212, n_221);
  DFC3 \temp_reg_reg[12] (.RN (n_252), .C (clk), .D (n_216), .Q
       (temp_reg[12]), .QN (UNCONNECTED3));
  wire w81, w82, w83, w84, w85, w86, w87, w88;
  wire w89, w90, w91, w92, w93, w94;
  nand g100 (n_221, w88, w94);
  or g99 (w94, w93, n_21);
  and g98 (w93, w90, w92);
  nand g97 (w92, w91, n_190);
  not g96 (w91, P_reg[13]);
  nand g95 (w90, w89, P_reg[13]);
  not g94 (w89, n_190);
  nand g93 (w88, w85, w87, n_21);
  nand g92 (w87, w86, n_190);
  not g91 (w86, P_reg[13]);
  nand g90 (w85, w84, P_reg[13]);
  not g89 (w84, n_190);
  and g8170 (n_220, w82, w83);
  or g88 (w83, n_190, P_reg[13]);
  or g87 (w82, w81, n_21);
  and g86 (w81, n_190, P_reg[13]);
  wire w95, w96, w97, w98, w99, w100, w101, w102;
  wire w103, w104, w105, w106, w107, w108;
  nand g115 (n_219, w102, w108);
  or g114 (w108, w107, A_reg[13]);
  and g113 (w107, w104, w106);
  nand g112 (w106, w105, n_188);
  not g111 (w105, P_reg[13]);
  nand g110 (w104, w103, P_reg[13]);
  not g109 (w103, n_188);
  nand g108 (w102, w99, w101, A_reg[13]);
  nand g107 (w101, w100, n_188);
  not g106 (w100, P_reg[13]);
  nand g105 (w99, w98, P_reg[13]);
  not g104 (w98, n_188);
  and g8169 (n_218, w96, w97);
  or g103 (w97, n_188, P_reg[13]);
  or g102 (w96, w95, A_reg[13]);
  and g101 (w95, n_188, P_reg[13]);
  DFEC1 \S_reg_reg[15] (.RN (n_252), .C (clk), .D (n_209), .E (n_217),
       .Q (S_reg[15]), .QN (n_1));
  not g8168 (n_216, n_214);
  wire w109, w110;
  nand g8148 (n_215, w109, w110);
  nand g117 (w110, a_in[7], n_208);
  or g116 (w109, a_in[7], n_208);
  nor g8171 (n_214, n_210, n_213);
  DFC3 \temp_reg_reg[9] (.RN (n_252), .C (clk), .D (n_211), .Q
       (temp_reg[9]), .QN (n_8));
  DFC3 \r_reg_reg[1] (.RN (n_252), .C (clk), .D (n_203), .Q (r_out[1]),
       .QN (UNCONNECTED4));
  DFC3 \temp_reg_reg[11] (.RN (n_252), .C (clk), .D (n_206), .Q
       (temp_reg[11]), .QN (UNCONNECTED5));
  DFC3 \r_reg_reg[2] (.RN (n_252), .C (clk), .D (n_207), .Q (r_out[2]),
       .QN (UNCONNECTED6));
  DFC3 \r_reg_reg[3] (.RN (n_252), .C (clk), .D (n_196), .Q (r_out[3]),
       .QN (UNCONNECTED7));
  DFC3 \r_reg_reg[4] (.RN (n_252), .C (clk), .D (n_192), .Q (r_out[4]),
       .QN (UNCONNECTED8));
  DFC3 \r_reg_reg[6] (.RN (n_252), .C (clk), .D (n_198), .Q (r_out[6]),
       .QN (UNCONNECTED9));
  DFC3 \r_reg_reg[7] (.RN (n_252), .C (clk), .D (n_197), .Q (r_out[7]),
       .QN (UNCONNECTED10));
  DFC3 \r_reg_reg[8] (.RN (n_252), .C (clk), .D (n_202), .Q (r_out[8]),
       .QN (UNCONNECTED11));
  DFC3 \i_reg_reg[3] (.RN (n_252), .C (clk), .D (n_205), .Q (i_reg[3]),
       .QN (n_6));
  wire w111;
  nor g8178 (n_213, w111, n_74);
  and g118 (w111, n_212, n_191);
  wire w112;
  nand g8172 (n_211, w112, n_273, n_170);
  or g119 (w112, n_131, n_223);
  wire w113;
  nor g8177 (n_210, w113, n_94);
  and g120 (w113, n_223, n_189);
  DFC3 \r_reg_reg[0] (.RN (n_252), .C (clk), .D (n_204), .Q (r_out[0]),
       .QN (UNCONNECTED12));
  DFC3 \r_reg_reg[10] (.RN (n_252), .C (clk), .D (n_194), .Q
       (r_out[10]), .QN (UNCONNECTED13));
  DFC3 \r_reg_reg[13] (.RN (n_252), .C (clk), .D (n_200), .Q
       (r_out[13]), .QN (UNCONNECTED14));
  DFC3 \r_reg_reg[11] (.RN (n_252), .C (clk), .D (n_193), .Q
       (r_out[11]), .QN (UNCONNECTED15));
  DFC3 \r_reg_reg[5] (.RN (n_252), .C (clk), .D (n_199), .Q (r_out[5]),
       .QN (UNCONNECTED16));
  DFC3 \r_reg_reg[9] (.RN (n_252), .C (clk), .D (n_195), .Q (r_out[9]),
       .QN (UNCONNECTED17));
  DFC3 \r_reg_reg[15] (.RN (n_252), .C (clk), .D (n_201), .Q
       (r_out[15]), .QN (UNCONNECTED18));
  wire w114, w115, w116, w117;
  nand g125 (n_209, w115, w117);
  nand g124 (w117, w116, n_4);
  not g123 (w116, n_147);
  nand g122 (w115, w114, n_147);
  not g121 (w114, n_4);
  and g8152 (n_208, n_4, n_147);
  DFEC1 \S_reg_reg[14] (.RN (n_252), .C (clk), .D (n_148), .E (n_217),
       .Q (S_reg[14]), .QN (n_2));
  DFC3 \P_reg_reg[5] (.RN (n_252), .C (clk), .D (n_176), .Q (P_reg[5]),
       .QN (n_23));
  DFC3 \P_reg_reg[8] (.RN (n_252), .C (clk), .D (n_166), .Q (P_reg[8]),
       .QN (n_20));
  DFC3 \P_reg_reg[2] (.RN (n_252), .C (clk), .D (n_171), .Q (P_reg[2]),
       .QN (UNCONNECTED19));
  DFC3 \P_reg_reg[4] (.RN (n_252), .C (clk), .D (n_177), .Q (P_reg[4]),
       .QN (n_10));
  DFC3 \P_reg_reg[3] (.RN (n_252), .C (clk), .D (n_169), .Q (P_reg[3]),
       .QN (UNCONNECTED20));
  DFC3 \P_reg_reg[7] (.RN (n_252), .C (clk), .D (n_173), .Q (P_reg[7]),
       .QN (n_14));
  DFC3 \P_reg_reg[6] (.RN (n_252), .C (clk), .D (n_174), .Q (P_reg[6]),
       .QN (n_13));
  DFC3 \P_reg_reg[1] (.RN (n_252), .C (clk), .D (n_165), .Q (P_reg[1]),
       .QN (n_27));
  not g8209 (n_207, n_168);
  wire w118;
  nand g8195 (n_206, w118, n_152);
  or g126 (w118, n_241, n_136);
  wire w119;
  nand g8194 (n_205, w119, n_96, n_145);
  or g127 (w119, n_66, n_133);
  not g8211 (n_204, n_172);
  not g8210 (n_203, n_167);
  DFC3 \P_reg_reg[14] (.RN (n_252), .C (clk), .D (n_149), .Q (n_162),
       .QN (P_reg[14]));
  DFC3 \P_reg_reg[0] (.RN (n_252), .C (clk), .D (n_154), .Q (P_reg[0]),
       .QN (UNCONNECTED21));
  DFC3 \P_reg_reg[12] (.RN (n_252), .C (clk), .D (n_156), .Q
       (P_reg[12]), .QN (n_187));
  DFC3 \P_reg_reg[11] (.RN (n_252), .C (clk), .D (n_153), .Q
       (P_reg[11]), .QN (n_100));
  DFC3 \P_reg_reg[15] (.RN (n_252), .C (clk), .D (n_155), .Q
       (P_reg[15]), .QN (n_236));
  DFC3 \P_reg_reg[9] (.RN (n_252), .C (clk), .D (n_157), .Q (P_reg[9]),
       .QN (n_7));
  DFC3 \P_reg_reg[10] (.RN (n_252), .C (clk), .D (n_159), .Q
       (P_reg[10]), .QN (n_36));
  not g8237 (n_202, n_185);
  not g8242 (n_201, n_178);
  not g8233 (n_200, n_163);
  not g8234 (n_199, n_161);
  not g8235 (n_198, n_160);
  not g8236 (n_197, n_179);
  not g8212 (n_196, n_164);
  not g8238 (n_195, n_182);
  not g8239 (n_194, n_181);
  not g8240 (n_193, n_180);
  not g8241 (n_192, n_186);
  DFC3 \r_reg_reg[12] (.RN (n_252), .C (clk), .D (n_158), .Q
       (r_out[12]), .QN (n_12));
  wire w120, w121, w122, w123, w124, w125, w126, w127;
  wire w128, w129, w130, w131, w132, w133;
  nand g142 (n_191, w127, w133);
  or g141 (w133, w132, n_5);
  and g140 (w132, w129, w131);
  nand g139 (w131, w130, n_101);
  not g138 (w130, n_187);
  nand g137 (w129, w128, n_187);
  not g136 (w128, n_101);
  nand g135 (w127, w124, w126, n_5);
  nand g134 (w126, w125, n_101);
  not g133 (w125, n_187);
  nand g132 (w124, w123, n_187);
  not g131 (w123, n_101);
  and g8213 (n_190, w121, w122);
  or g130 (w122, n_101, n_187);
  or g129 (w121, w120, n_5);
  and g128 (w120, n_101, n_187);
  wire w134, w135, w136, w137, w138, w139, w140, w141;
  wire w142, w143, w144, w145, w146, w147;
  nand g157 (n_189, w141, w147);
  or g156 (w147, w146, A_reg[12]);
  and g155 (w146, w143, w145);
  nand g154 (w145, w144, n_103);
  not g153 (w144, n_187);
  nand g152 (w143, w142, n_187);
  not g151 (w142, n_103);
  nand g150 (w141, w138, w140, A_reg[12]);
  nand g149 (w140, w139, n_103);
  not g148 (w139, n_187);
  nand g147 (w138, w137, n_187);
  not g146 (w137, n_103);
  and g8214 (n_188, w135, w136);
  or g145 (w136, n_103, n_187);
  or g144 (w135, w134, A_reg[12]);
  and g143 (w134, n_103, n_187);
  wire w148, w149;
  and g8253 (n_186, w148, w149);
  nand g159 (w149, P_reg[5], n_183);
  nand g158 (w148, r_out[4], n_184);
  wire w150, w151;
  and g8248 (n_185, w150, w151);
  nand g161 (w151, P_reg[9], n_183);
  nand g160 (w150, r_out[8], n_184);
  wire w152, w153;
  and g8249 (n_182, w152, w153);
  nand g163 (w153, P_reg[10], n_183);
  nand g162 (w152, r_out[9], n_184);
  wire w154, w155;
  and g8250 (n_181, w154, w155);
  nand g165 (w155, P_reg[11], n_183);
  nand g164 (w154, r_out[10], n_184);
  wire w156, w157;
  and g8251 (n_180, w156, w157);
  nand g167 (w157, P_reg[12], n_183);
  nand g166 (w156, r_out[11], n_184);
  wire w158, w159;
  and g8247 (n_179, w158, w159);
  nand g169 (w159, P_reg[8], n_183);
  nand g168 (w158, r_out[7], n_184);
  wire w160, w161;
  and g8254 (n_178, w160, w161);
  nand g171 (w161, P_reg[15], n_183);
  nand g170 (w160, r_out[15], n_184);
  wire w162, w163;
  nand g8256 (n_177, w162, w163);
  or g173 (w163, temp_reg[5], n_175);
  or g172 (w162, n_60, n_125);
  wire w164, w165;
  nand g8257 (n_176, w164, w165);
  or g175 (w165, temp_reg[6], n_175);
  or g174 (w164, n_65, n_126);
  wire w166, w167;
  nand g8258 (n_174, w166, w167);
  or g177 (w167, temp_reg[7], n_175);
  or g176 (w166, n_61, n_124);
  wire w168, w169;
  nand g8259 (n_173, w168, w169);
  or g179 (w169, temp_reg[8], n_175);
  or g178 (w168, n_62, n_123);
  wire w170, w171;
  and g8218 (n_172, w170, w171);
  nand g181 (w171, P_reg[1], n_183);
  nand g180 (w170, r_out[0], n_184);
  wire w172, w173;
  nand g8261 (n_171, w172, w173);
  or g183 (w173, temp_reg[3], n_175);
  or g182 (w172, n_59, n_120);
  wire w174;
  nand g8197 (n_170, w174, n_49);
  or g184 (w174, n_129, n_132);
  wire w175, w176;
  nand g8262 (n_169, w175, w176);
  or g186 (w176, temp_reg[4], n_175);
  or g185 (w175, n_58, n_119);
  wire w177, w178;
  and g8216 (n_168, w177, w178);
  nand g188 (w178, P_reg[3], n_183);
  nand g187 (w177, r_out[2], n_184);
  wire w179, w180;
  and g8217 (n_167, w179, w180);
  nand g190 (w180, P_reg[2], n_183);
  nand g189 (w179, r_out[1], n_184);
  wire w181, w182;
  nand g8260 (n_166, w181, w182);
  or g192 (w182, n_8, n_175);
  or g191 (w181, n_57, n_122);
  wire w183, w184;
  nand g8219 (n_165, w183, w184);
  or g194 (w184, temp_reg[2], n_175);
  or g193 (w183, n_56, n_121);
  wire w185, w186;
  and g8221 (n_164, w185, w186);
  nand g196 (w186, P_reg[4], n_183);
  nand g195 (w185, r_out[3], n_184);
  wire w187, w188;
  and g8244 (n_163, w187, w188);
  nand g198 (w188, n_162, n_183);
  nand g197 (w187, r_out[13], n_184);
  wire w189, w190;
  and g8245 (n_161, w189, w190);
  nand g200 (w190, P_reg[6], n_183);
  nand g199 (w189, r_out[5], n_184);
  wire w191, w192;
  and g8246 (n_160, w191, w192);
  nand g202 (w192, P_reg[7], n_183);
  nand g201 (w191, r_out[6], n_184);
  not g8263 (n_159, n_146);
  wire w193, w194;
  nand g8252 (n_158, w193, w194);
  or g204 (w194, P_reg[13], n_114);
  or g203 (w193, n_12, n_118);
  DFC3 \i_reg_reg[2] (.RN (n_252), .C (clk), .D (n_128), .Q (i_reg[2]),
       .QN (n_41));
  not g8264 (n_157, n_144);
  not g8274 (n_156, n_141);
  DFC3 \i_reg_reg[1] (.RN (n_252), .C (clk), .D (n_135), .Q (i_reg[1]),
       .QN (n_9));
  not g8276 (n_155, n_139);
  not g8277 (n_154, n_138);
  not g8278 (n_153, n_137);
  wire w195, w196;
  nand g8215 (n_152, w195, w196);
  or g206 (w196, P_reg[11], n_150);
  or g205 (w195, n_151, n_117);
  not g8275 (n_149, n_140);
  DFC3 \P_reg_reg[13] (.RN (n_252), .C (clk), .D (n_127), .Q (n_15),
       .QN (P_reg[13]));
  wire w197, w198, w199, w200;
  nand g211 (n_148, w198, w200);
  nand g210 (w200, w199, n_0);
  not g209 (w199, n_105);
  nand g208 (w198, w197, n_105);
  not g207 (w197, n_0);
  and g8162 (n_147, n_0, n_105);
  wire w201, w202;
  and g8267 (n_146, w201, w202);
  nand g213 (w202, temp_reg[11], n_142);
  nand g212 (w201, P_reg[10], n_143);
  nand g8269 (n_145, i_reg[3], n_116);
  wire w203, w204;
  and g8270 (n_144, w203, w204);
  nand g215 (w204, temp_reg[10], n_142);
  nand g214 (w203, P_reg[9], n_143);
  DFEC1 \S_reg_reg[13] (.RN (n_252), .C (clk), .D (n_106), .E (n_217),
       .Q (S_reg[13]), .QN (n_21));
  wire w205, w206;
  and g8280 (n_141, w205, w206);
  nand g217 (w206, temp_reg[13], n_142);
  nand g216 (w205, P_reg[12], n_143);
  DFC3 \temp_reg_reg[10] (.RN (n_252), .C (clk), .D (n_115), .Q
       (temp_reg[10]), .QN (UNCONNECTED22));
  wire w207, w208;
  and g8282 (n_140, w207, w208);
  nand g219 (w208, temp_reg[15], n_142);
  nand g218 (w207, n_162, n_143);
  wire w209, w210;
  and g8283 (n_139, w209, w210);
  nand g221 (w210, temp_reg[16], n_142);
  nand g220 (w209, P_reg[15], n_143);
  wire w211, w212;
  and g8284 (n_138, w211, w212);
  nand g223 (w212, temp_reg[1], n_142);
  nand g222 (w211, P_reg[0], n_143);
  wire w213, w214;
  and g8287 (n_137, w213, w214);
  nand g225 (w214, temp_reg[12], n_142);
  nand g224 (w213, P_reg[11], n_143);
  wire w215, w216;
  nand g8279 (n_136, w215, w216);
  or g227 (w216, temp_reg[11], n_246);
  or g226 (w215, n_233, n_112);
  JKC3 \i_reg_reg[0] (.RN (n_252), .C (clk), .J (n_92), .K (n_134), .Q
       (i_reg[0]), .QN (UNCONNECTED23));
  wire w217, w218;
  nand g8286 (n_135, w217, w218);
  or g229 (w218, n_32, n_133);
  or g228 (w217, n_9, n_134);
  wire w219;
  nor g8271 (n_132, w219, n_7);
  and g230 (w219, n_130, n_131);
  wire w220;
  nor g8266 (n_129, w220, A_reg[9]);
  and g231 (w220, n_51, n_131);
  wire w221, w222;
  nand g8285 (n_128, w221, w222);
  or g233 (w222, n_133, n_42);
  or g232 (w221, n_41, n_134);
  wire w223, w224;
  nand g8281 (n_127, w223, w224);
  or g235 (w224, n_11, n_175);
  or g234 (w223, P_reg[13], n_107);
  DFC3 \temp_reg_reg[2] (.RN (n_252), .C (clk), .D (n_110), .Q
       (UNCONNECTED24), .QN (temp_reg[2]));
  DFC3 \temp_reg_reg[3] (.RN (n_252), .C (clk), .D (n_108), .Q
       (UNCONNECTED25), .QN (temp_reg[3]));
  DFC3 \temp_reg_reg[1] (.RN (n_252), .C (clk), .D (n_109), .Q
       (temp_reg[1]), .QN (UNCONNECTED26));
  DFC3 \state_reg_reg[0] (.RN (n_252), .C (clk), .D (n_113), .Q
       (state_reg[0]), .QN (n_3));
  nor g8288 (n_126, n_143, b_in[4]);
  nor g8289 (n_125, n_143, b_in[3]);
  nor g8290 (n_124, n_143, b_in[5]);
  nor g8291 (n_123, n_143, b_in[6]);
  nor g8292 (n_122, n_143, b_in[7]);
  nor g8293 (n_121, n_143, b_in[0]);
  nor g8299 (n_120, n_143, b_in[1]);
  nor g8297 (n_119, n_143, b_in[2]);
  DFC3 \state_reg_reg[2] (.RN (n_252), .C (clk), .D (n_111), .Q
       (state_reg[2]), .QN (n_16));
  not g8295 (n_184, n_118);
  nor g8296 (n_117, n_102, n_130);
  nand g8298 (n_116, n_46, n_134);
  wire w225;
  nand g8300 (n_115, w225, n_95);
  or g236 (w225, n_241, n_73);
  wire w226;
  nand g8302 (n_118, w226, n_114);
  or g237 (w226, n_77, n_217, n_142);
  nand g8196 (n_113, n_44, n_175, n_87);
  not g8303 (n_112, n_104);
  DFC3 \temp_reg_reg[4] (.RN (n_252), .C (clk), .D (n_90), .Q
       (UNCONNECTED27), .QN (temp_reg[4]));
  DFC3 \temp_reg_reg[5] (.RN (n_252), .C (clk), .D (n_85), .Q
       (UNCONNECTED28), .QN (temp_reg[5]));
  DFC3 \temp_reg_reg[7] (.RN (n_252), .C (clk), .D (n_82), .Q
       (UNCONNECTED29), .QN (temp_reg[7]));
  DFC3 \temp_reg_reg[8] (.RN (n_252), .C (clk), .D (n_83), .Q
       (UNCONNECTED30), .QN (temp_reg[8]));
  not g8243 (n_111, n_97);
  wire w227;
  nand g8327 (n_110, w227, n_78);
  or g238 (w227, n_223, temp_reg[2]);
  not g8322 (n_109, n_93);
  wire w228;
  nand g8326 (n_108, w228, n_80);
  or g239 (w228, n_223, temp_reg[3]);
  DFC3 \temp_reg_reg[6] (.RN (n_252), .C (clk), .D (n_81), .Q
       (UNCONNECTED31), .QN (temp_reg[6]));
  DFC3 \state_reg_reg[1] (.RN (n_252), .C (clk), .D (n_89), .Q
       (state_reg[1]), .QN (n_35));
  not g8313 (n_143, n_107);
  wire w229, w230, w231, w232;
  nand g244 (n_106, w230, w232);
  nand g243 (w232, w231, n_22);
  not g242 (w231, n_67);
  nand g241 (w230, w229, n_67);
  not g240 (w229, n_22);
  and g8173 (n_105, n_22, n_67);
  wire w233, w234, w235, w236, w237, w238, w239, w240;
  wire w241, w242, w243, w244, w245, w246;
  nand g259 (n_104, w240, w246);
  or g258 (w246, w245, A_reg[11]);
  and g257 (w245, w242, w244);
  nand g256 (w244, w243, n_54);
  not g255 (w243, n_100);
  nand g254 (w242, w241, n_100);
  not g253 (w241, n_54);
  nand g252 (w240, w237, w239, A_reg[11]);
  nand g251 (w239, w238, n_54);
  not g250 (w238, n_100);
  nand g249 (w237, w236, n_100);
  not g248 (w236, n_54);
  and g8305 (n_103, w234, w235);
  or g247 (w235, n_54, n_100);
  or g246 (w234, w233, A_reg[11]);
  and g245 (w233, n_54, n_100);
  wire w247, w248, w249, w250, w251, w252, w253, w254;
  wire w255, w256, w257, w258, w259, w260;
  nand g274 (n_102, w254, w260);
  or g273 (w260, w259, n_17);
  and g272 (w259, w256, w258);
  nand g271 (w258, w257, n_55);
  not g270 (w257, n_100);
  nand g269 (w256, w255, n_100);
  not g268 (w255, n_55);
  nand g267 (w254, w251, w253, n_17);
  nand g266 (w253, w252, n_55);
  not g265 (w252, n_100);
  nand g264 (w251, w250, n_100);
  not g263 (w250, n_55);
  and g8304 (n_101, w248, w249);
  or g262 (w249, n_55, n_100);
  or g261 (w248, w247, n_17);
  and g260 (w247, n_55, n_100);
  wire w261;
  nor g8314 (n_99, w261, n_246);
  and g275 (w261, temp_reg[13], n_98);
  DFEC1 \S_reg_reg[12] (.RN (n_252), .C (clk), .D (n_68), .E (n_217),
       .Q (S_reg[12]), .QN (n_5));
  wire w262, w263;
  and g8255 (n_97, w262, w263);
  nand g277 (w263, n_96, n_45);
  nand g276 (w262, n_88, n_86);
  wire w264, w265;
  nand g8315 (n_95, w264, w265);
  or g279 (w265, P_reg[10], n_150);
  or g278 (w264, n_151, n_72);
  wire w266;
  nor g8316 (n_94, w266, n_246);
  and g280 (w266, temp_reg[12], n_98);
  wire w267, w268;
  and g8325 (n_93, w267, w268);
  nand g282 (w268, temp_reg[1], n_233);
  nand g281 (w267, P_reg[1], n_79);
  nor g8321 (n_107, n_91, n_92);
  wire w269;
  nor g8319 (n_131, w269, n_246);
  and g283 (w269, temp_reg[9], n_98);
  nor g8320 (n_134, n_91, n_142);
  wire w270, w271;
  nand g8330 (n_90, w270, w271);
  or g285 (w271, temp_reg[4], n_223);
  or g284 (w270, n_10, n_84);
  wire w272;
  nand g8220 (n_89, w272, n_38);
  or g286 (w272, n_69, n_88);
  wire w273;
  nand g8268 (n_87, w273, n_86);
  or g287 (w273, n_27, P_reg[0]);
  wire w274, w275;
  nand g8331 (n_85, w274, w275);
  or g289 (w275, temp_reg[5], n_223);
  or g288 (w274, n_23, n_84);
  wire w276, w277;
  nand g8334 (n_83, w276, w277);
  or g291 (w277, temp_reg[8], n_223);
  or g290 (w276, n_20, n_84);
  wire w278, w279;
  nand g8333 (n_82, w278, w279);
  or g293 (w279, temp_reg[7], n_223);
  or g292 (w278, n_14, n_84);
  wire w280, w281;
  nand g8332 (n_81, w280, w281);
  or g295 (w281, temp_reg[6], n_223);
  or g294 (w280, n_13, n_84);
  nand g8345 (n_80, P_reg[3], n_79);
  nand g8347 (n_78, P_reg[2], n_79);
  nand g8328 (n_91, n_37, n_114, n_84);
  nand g8348 (n_77, start, n_133, n_84);
  not g8352 (n_76, n_75);
  DFEC1 \A_reg_reg[15] (.RN (n_252), .C (clk), .D (a_in[6]), .E
       (n_217), .Q (UNCONNECTED32), .QN (A_reg[15]));
  DFEC1 \A_reg_reg[16] (.RN (n_252), .C (clk), .D (a_in[7]), .E
       (n_217), .Q (A_reg[16]), .QN (UNCONNECTED33));
  DFEC1 \A_reg_reg[13] (.RN (n_252), .C (clk), .D (a_in[4]), .E
       (n_217), .Q (UNCONNECTED34), .QN (A_reg[13]));
  DFEC1 \A_reg_reg[14] (.RN (n_252), .C (clk), .D (a_in[5]), .E
       (n_217), .Q (UNCONNECTED35), .QN (A_reg[14]));
  DFEC1 \A_reg_reg[12] (.RN (n_252), .C (clk), .D (a_in[3]), .E
       (n_217), .Q (UNCONNECTED36), .QN (A_reg[12]));
  DFEC1 \S_reg_reg[11] (.RN (n_252), .C (clk), .D (n_40), .E (n_217),
       .Q (S_reg[11]), .QN (n_17));
  DFEC1 \A_reg_reg[10] (.RN (n_252), .C (clk), .D (a_in[1]), .E
       (n_217), .Q (A_reg[10]), .QN (UNCONNECTED37));
  DFEC1 \A_reg_reg[9] (.RN (n_252), .C (clk), .D (a_in[0]), .E (n_217),
       .Q (n_19), .QN (A_reg[9]));
  DFEC1 \S_reg_reg[10] (.RN (n_252), .C (clk), .D (n_26), .E (n_217),
       .Q (S_reg[10]), .QN (UNCONNECTED38));
  wire w282;
  nor g8344 (n_74, w282, n_150);
  and g296 (w282, P_reg[12], n_70);
  DFEC1 \A_reg_reg[11] (.RN (n_252), .C (clk), .D (a_in[2]), .E
       (n_217), .Q (UNCONNECTED39), .QN (A_reg[11]));
  wire w283, w284;
  nand g8335 (n_73, w283, w284);
  or g298 (w284, temp_reg[10], n_246);
  or g297 (w283, n_47, n_233);
  nor g8346 (n_72, n_130, n_50);
  wire w285;
  nor g8349 (n_71, w285, n_150);
  and g299 (w285, n_15, n_70);
  nor g8360 (n_75, n_130, n_64);
  not g8294 (n_86, n_69);
  not g8353 (n_79, n_84);
  not g8343 (n_98, n_241);
  wire w286, w287, w288, w289;
  nand g304 (n_68, w287, w289);
  nand g303 (w289, w288, n_18);
  not g302 (w288, n_39);
  nand g301 (w287, w286, n_39);
  not g300 (w286, n_18);
  and g8265 (n_67, n_18, n_39);
  nand g8301 (n_69, n_92, n_66);
  nor g8361 (n_84, n_70, n_246);
  nand g8359 (n_249, n_151, n_63);
  nor g8351 (n_241, n_233, n_246);
  wire w290;
  nor g8355 (n_65, w290, n_217);
  and g305 (w290, P_reg[5], n_175);
  not g8374 (n_64, n_63);
  wire w291;
  nor g8356 (n_62, w291, n_217);
  and g306 (w291, P_reg[7], n_175);
  not g8375 (n_130, n_70);
  not g8354 (n_223, n_233);
  wire w292;
  nor g8357 (n_61, w292, n_217);
  and g307 (w292, P_reg[6], n_175);
  wire w293;
  nor g8358 (n_60, w293, n_217);
  and g308 (w293, P_reg[4], n_175);
  wire w294;
  nor g8364 (n_59, w294, n_217);
  and g309 (w294, P_reg[2], n_175);
  wire w295;
  nor g8365 (n_58, w295, n_217);
  and g310 (w295, P_reg[3], n_175);
  wire w296;
  nor g8366 (n_57, w296, n_217);
  and g311 (w296, P_reg[8], n_175);
  wire w297;
  nor g8369 (n_56, w297, n_217);
  and g312 (w297, P_reg[1], n_175);
  wire w298;
  nand g8371 (n_55, w298, n_52);
  or g313 (w298, n_53, S_reg[10]);
  wire w299;
  nand g8370 (n_54, w299, n_52);
  or g314 (w299, n_53, A_reg[10]);
  nand g8376 (n_63, n_236, n_51);
  nand g8377 (n_70, n_51, n_212);
  wire w300, w301, w302, w303, w304, w305, w306, w307;
  wire w308, w309, w310;
  nand g8363 (n_50, w304, w310);
  or g325 (w310, w309, P_reg[10]);
  and g324 (w309, w306, w308);
  nand g323 (w308, w307, n_49);
  not g322 (w307, S_reg[10]);
  nand g321 (w306, w305, S_reg[10]);
  not g320 (w305, n_49);
  nand g319 (w304, w301, w303, P_reg[10]);
  nand g318 (w303, w302, n_49);
  not g317 (w302, S_reg[10]);
  nand g316 (w301, w300, S_reg[10]);
  not g315 (w300, n_49);
  wire w311, w312, w313, w314, w315, w316, w317;
  nand g8367 (n_47, w313, w317);
  or g332 (w317, w316, P_reg[10]);
  and g331 (w316, w314, w315);
  nand g330 (w315, A_reg[10], n_49);
  or g329 (w314, A_reg[10], n_49);
  nand g328 (w313, w311, w312, P_reg[10]);
  nand g327 (w312, A_reg[10], n_49);
  or g326 (w311, A_reg[10], n_49);
  nand g8318 (n_66, n_6, n_46);
  nand g8362 (n_233, n_175, n_45);
  nand g8372 (n_44, start, ready);
  not g8389 (n_142, n_175);
  not g8390 (n_217, n_96);
  wire w318, w319, w320, w321;
  nand g337 (n_42, w319, w321);
  nand g336 (w321, w320, n_41);
  not g335 (w320, n_31);
  nand g334 (w319, w318, n_31);
  not g333 (w318, n_41);
  and g8323 (n_46, n_41, n_31);
  wire w322, w323, w324, w325;
  nand g342 (n_40, w323, w325);
  nand g341 (w325, w324, n_24);
  not g340 (w324, n_25);
  nand g339 (w323, w322, n_25);
  not g338 (w322, n_24);
  and g8324 (n_39, n_24, n_25);
  nor g8373 (n_45, n_183, n_38);
  not g8388 (n_51, n_150);
  nand g8396 (n_96, n_35, n_34);
  nand g8395 (n_175, state_reg[1], n_30);
  not g8378 (ready, n_37);
  nand g8383 (n_52, n_36, n_49);
  not g8381 (n_114, n_183);
  not g8380 (n_212, n_151);
  nor g8382 (n_53, n_49, n_36);
  not g8379 (n_92, n_133);
  nor g8393 (n_150, n_29, state_reg[1]);
  nor g8394 (n_246, n_33, n_35);
  nand g8384 (n_37, n_35, n_38);
  nand g8385 (n_133, state_reg[1], n_38);
  nor g8386 (n_151, n_28, state_reg[1]);
  not g8401 (n_34, n_33);
  wire w326;
  nor g8391 (n_32, w326, n_31);
  and g343 (w326, i_reg[0], i_reg[1]);
  not g8402 (n_30, n_29);
  nor g8387 (n_183, n_28, n_35);
  nand g8404 (n_88, P_reg[0], n_27);
  nand g8400 (n_49, n_19, P_reg[9]);
  wire w327, w328, w329, w330;
  nand g8392 (n_26, w328, w330);
  nand g347 (w330, w329, a_in[1]);
  not g346 (w329, a_in[0]);
  nand g345 (w328, w327, a_in[0]);
  not g344 (w327, a_in[1]);
  nand g8403 (n_33, state_reg[0], n_16);
  nand g8405 (n_29, state_reg[2], n_3);
  nor g8406 (n_25, a_in[1], a_in[0]);
  nor g8398 (n_31, i_reg[1], i_reg[0]);
  nand g8397 (n_28, state_reg[0], state_reg[2]);
  nor g8399 (n_38, state_reg[2], state_reg[0]);
  not g8436 (n_24, a_in[2]);
  not g8413 (n_22, a_in[4]);
  not g8435 (n_18, a_in[3]);
  not g8434 (n_4, a_in[6]);
  not g8415 (n_0, a_in[5]);
  not g8440 (n_252, rst);
  nand g2 (n_273, n_151, P_reg[9]);
endmodule


module DFC3(C, D, RN, Q, QN);
  input C, D, RN;
  output Q, QN;
  wire C, D, RN;
  wire Q, QN;
  wire next_state;
  reg  qi;
  assign #1 Q = qi, QN = !qi;
  assign next_state = D;
  always 
    @(posedge C or negedge RN) 
      if (!RN) 
        qi <= 0;
      else qi <= next_state;
  initial 
    qi <= 1'b0;
endmodule

module DFEC1(C, D, E, RN, Q, QN);
  input C, D, E, RN;
  output Q, QN;
  wire C, D, E, RN;
  wire Q, QN;
  wire next_state, w331, w332, w333;
  reg  qi;
  assign #1 Q = qi, QN = !qi;
  not g348 (w331, E);
  nand g349 (w332, w331, qi);
  nand g350 (w333, D, E);
  nand g351 (next_state, w332, w333);
  always 
    @(posedge C or negedge RN) 
      if (!RN) 
        qi <= 0;
      else qi <= next_state;
  initial 
    qi <= 1'b0;
endmodule

module JKC3(C, J, K, RN, Q, QN);
  input C, J, K, RN;
  output Q, QN;
  wire C, J, K, RN;
  wire Q, QN;
  wire next_state, w334, w335, w336, w337;
  reg  qi;
  assign #1 Q = qi, QN = !qi;
  not g352 (w334, qi);
  nand g353 (w335, w334, J);
  not g354 (w336, K);
  nand g355 (w337, w336, qi);
  nand g356 (next_state, w335, w337);
  always 
    @(posedge C or negedge RN) 
      if (!RN) 
        qi <= 0;
      else qi <= next_state;
  initial 
    qi <= 1'b0;
endmodule
